### ISSUE TITLE
Wrong naming for PactMatchers REGEXes

### ISSUE THREAD

**Issue by victorenaud** [matthewshirley/pact_dart#13]
In the file `matchers.dart` there is an inversion of `UUID_REGEX` and `EMAIL_REGEX` constants.
As `EMAIL_REGEX` contains the uuid regex, and `UUID_REGEX` contains the email regex.

But `email()` and `uuid()` use the correct regex.

**Comment by matthewshirley** [comment]
Thank you for noticing! I was probably tired when committing that code. 😅 

I will correct this shortly.
